CREATE TABLE IF NOT EXISTS sketchizi_users
(
    id               BIGSERIAL PRIMARY KEY,
    provider         VARCHAR(32)  NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    email            VARCHAR(320),
    display_name     VARCHAR(255),
    picture_url      TEXT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_sketchizi_users_provider_subject
        UNIQUE (provider, provider_subject)
);

-- Spring Session JDBC schema (PostgreSQL). Keep these statements idempotent because
-- spring.sql.init.mode is always and this script runs on each service startup.
-- Existing session rows and unrelated tables are not dropped or recreated.
CREATE TABLE IF NOT EXISTS SPRING_SESSION
(
    PRIMARY_ID             CHAR(36)     NOT NULL,
    SESSION_ID             CHAR(36)     NOT NULL,
    CREATION_TIME          BIGINT       NOT NULL,
    LAST_ACCESS_TIME       BIGINT       NOT NULL,
    MAX_INACTIVE_INTERVAL  INT          NOT NULL,
    EXPIRY_TIME            BIGINT       NOT NULL,
    PRINCIPAL_NAME          VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES
(
    SESSION_PRIMARY_ID  CHAR(36)     NOT NULL,
    ATTRIBUTE_NAME      VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES     BYTEA        NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK
        FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION (PRIMARY_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS SPRING_SESSION_ATTRIBUTES_IX1
    ON SPRING_SESSION_ATTRIBUTES (SESSION_PRIMARY_ID);
