import { CaptureUpdateAction } from "@excalidraw/excalidraw";

const MORE_TOOL_COMMANDS = [
  ["tools.insert-image", "Insert Image", "Tools", ["image", "picture", "insert image"], "", "image"],
  ["tools.frame", "Frame Tool", "Tools", ["frame", "frames"], "", "frame"],
  ["tools.web-embed", "Web Embed", "Tools", ["web", "embed", "iframe"], "", "embeddable"],
  ["tools.draw-to-shape", "Draw to Shape", "Tools", ["autoshape", "shape recognition"], "", "autoshape"],
  ["tools.laser", "Laser Pointer", "Tools", ["laser", "pointer", "presentation"], "", "laser"],
  ["tools.bucket-fill", "Bucket Fill", "Tools", ["bucket", "fill", "color"], "", "bucketfill"],
  ["tools.lasso", "Lasso Selection", "Tools", ["lasso", "select"], "", "lasso"],
];

export function createSketchiziCommandRegistry(context) {
  const {
    apiRef,
    canEdit,
    selectedCount,
    themeMode,
    setThemeMode,
    gridEnabled,
    toggleGrid,
    setMinimapOpen,
    fitDiagram,
    activateMoreTool,
    openPanel,
    startCollaboration,
    leaveOrEndCollaboration,
    requestEditAccess,
    collaborationRoom,
    collaborationPermission,
    currentFolder,
    fileActionsRef,
  } = context;

  const updateZoom = (operation) => {
    const api = apiRef.current;
    if (!api) return;
    const current = Number(api.getAppState?.().zoom?.value) || 1;
    const next = operation === "in"
      ? Math.min(8, current * 1.2)
      : operation === "out"
        ? Math.max(0.1, current / 1.2)
        : 1;
    api.updateScene?.({ appState: { ...api.getAppState(), zoom: { value: next } }, captureUpdate: CaptureUpdateAction.NEVER });
  };

  const openExcalidrawCommandPalette = () => {
    const api = apiRef.current;
    if (!api) return;
    api.updateScene?.({ appState: { ...api.getAppState(), openDialog: { name: "commandPalette" } } });
  };

  const commands = [];

  commands.push(
    ...MORE_TOOL_COMMANDS.map(([id, label, category, keywords, shortcut, tool]) => ({
      id,
      label,
      description: `Open the existing ${label.toLowerCase()} tool`,
      keywords,
      category,
      shortcut,
      icon: "◈",
      available: () => canEdit,
      execute: () => activateMoreTool(tool),
    })),
    {
      id: "tools.text-to-diagram",
      label: "Text to Diagram",
      description: "Open the existing Text to Diagram dialog",
      keywords: ["text", "diagram", "ai", "generate"],
      category: "Tools",
      shortcut: "",
      icon: "✿",
      available: () => canEdit,
      execute: () => activateMoreTool("text-to-diagram"),
    },
    {
      id: "tools.mermaid",
      label: "Mermaid to Excalidraw",
      description: "Open the existing Mermaid conversion dialog",
      keywords: ["mermaid", "diagram", "convert", "ai"],
      category: "Tools",
      shortcut: "",
      icon: "Y",
      available: () => canEdit,
      execute: () => activateMoreTool("mermaid"),
    },
    {
      id: "tools.wireframe-to-code",
      label: "Wireframe to Code",
      description: "Open the existing wireframe generation action",
      keywords: ["wireframe", "code", "magicframe", "ai"],
      category: "Tools",
      shortcut: "",
      icon: "✣",
      available: () => canEdit,
      execute: () => activateMoreTool("magicframe"),
    },
    {
      id: "tools.icon-library",
      label: "Open Icon Library",
      description: "Open Sketchizi's icon library",
      keywords: ["icon", "icons", "library", "uml", "mind map", "eraser"],
      category: "Tools",
      shortcut: "/",
      icon: "▧",
      available: () => canEdit,
      execute: () => openPanel("icon-library"),
    },
    {
      id: "layout.open",
      label: "Open Layout",
      description: "Open alignment, distribution and grid controls",
      keywords: ["layout", "align", "alignment", "distribute", "grid"],
      category: "Layout",
      shortcut: "L",
      icon: "⌗",
      available: () => true,
      execute: () => openPanel("layout"),
    },
    {
      id: "properties.open",
      label: "Open Properties",
      description: "Open properties and style controls for the current selection",
      keywords: ["properties", "style", "appearance", "stroke", "fill"],
      category: "Tools",
      shortcut: "P",
      icon: "◧",
      available: () => canEdit && selectedCount > 0,
      execute: () => openPanel("properties"),
    },
    {
      id: "view.zoom-in",
      label: "Zoom In",
      description: "Increase canvas zoom",
      keywords: ["zoom", "in", "magnify"],
      category: "View",
      shortcut: "Ctrl++",
      icon: "+",
      available: () => true,
      execute: () => updateZoom("in"),
    },
    {
      id: "view.zoom-out",
      label: "Zoom Out",
      description: "Decrease canvas zoom",
      keywords: ["zoom", "out", "shrink"],
      category: "View",
      shortcut: "Ctrl+-",
      icon: "−",
      available: () => true,
      execute: () => updateZoom("out"),
    },
    {
      id: "view.reset-zoom",
      label: "Reset Zoom",
      description: "Return canvas zoom to 100%",
      keywords: ["zoom", "reset", "100%"],
      category: "View",
      shortcut: "Ctrl+0",
      icon: "1:1",
      available: () => true,
      execute: () => updateZoom("reset"),
    },
    {
      id: "view.fit-canvas",
      label: "Fit to Canvas",
      description: "Fit the drawing into the viewport",
      keywords: ["fit", "canvas", "viewport", "diagram"],
      category: "View",
      shortcut: "F",
      icon: "□",
      available: () => true,
      execute: fitDiagram,
    },
    {
      id: "view.toggle-minimap",
      label: "Toggle Minimap",
      description: "Show or hide the canvas minimap",
      keywords: ["minimap", "map", "overview"],
      category: "View",
      shortcut: "M",
      icon: "▦",
      available: () => true,
      execute: () => setMinimapOpen((open) => !open),
    },
    {
      id: "view.toggle-theme",
      label: themeMode === "dark" ? "Switch to Light Theme" : "Switch to Dark Theme",
      description: "Toggle Sketchizi's light and dark theme",
      keywords: ["theme", "dark", "light", "appearance"],
      category: "View",
      shortcut: "D",
      icon: themeMode === "dark" ? "☀" : "☾",
      available: () => true,
      execute: () => setThemeMode((mode) => mode === "dark" ? "light" : "dark"),
    },
    {
      id: "view.toggle-grid",
      label: gridEnabled ? "Disable Grid Snapping" : "Enable Grid Snapping",
      description: "Toggle grid snapping while editing",
      keywords: ["grid", "snap", "snapping"],
      category: "View",
      shortcut: "⇧G",
      icon: "#",
      available: () => canEdit,
      execute: toggleGrid,
    },
    {
      id: "collaboration.start",
      label: "Start Collaboration",
      description: "Create a new collaboration room",
      keywords: ["collaboration", "collab", "room", "share"],
      category: "Collaboration",
      shortcut: "",
      icon: "◎",
      available: () => !collaborationRoom,
      execute: startCollaboration,
    },
    {
      id: "collaboration.open",
      label: "Open Collaboration",
      description: "Open the current collaboration details",
      keywords: ["collaboration", "collab", "details", "participants", "room"],
      category: "Collaboration",
      shortcut: "",
      icon: "◎",
      available: () => Boolean(collaborationRoom),
      execute: startCollaboration,
    },
    {
      id: "collaboration.request-edit",
      label: "Request Edit Access",
      description: "Ask the host to grant editing permission",
      keywords: ["edit", "access", "permission", "request", "viewer"],
      category: "Collaboration",
      shortcut: "",
      icon: "→",
      available: () => Boolean(collaborationRoom) && collaborationPermission === "viewer",
      execute: requestEditAccess,
    },
    {
      id: "collaboration.leave-or-end",
      label: collaborationPermission === "host" ? "End Collaboration" : "Leave Collaboration",
      description: collaborationPermission === "host" ? "End the current collaboration session" : "Leave the current collaboration session",
      keywords: ["collaboration", "collab", "leave", "end", "disconnect"],
      category: "Collaboration",
      shortcut: "",
      icon: "×",
      available: () => Boolean(collaborationRoom),
      execute: leaveOrEndCollaboration,
    },
    {
      id: "files.new",
      label: "New",
      description: "Create a new drawing using the existing file action",
      keywords: ["new", "file", "drawing", "blank"],
      category: "Files",
      shortcut: "",
      icon: "+",
      available: () => canEdit,
      execute: () => fileActionsRef.current.createNewFile?.(),
    },
    {
      id: "files.open",
      label: "Open",
      description: "Open a drawing using the existing file action",
      keywords: ["open", "load", "file", "drawing"],
      category: "Files",
      shortcut: "Ctrl+O",
      icon: "↥",
      available: () => canEdit,
      execute: () => fileActionsRef.current.openDrawingFromDisk?.(),
    },
    {
      id: "files.save",
      label: "Save",
      description: "Save the current drawing using the existing file action",
      keywords: ["save", "write", "file", "persist"],
      category: "Files",
      shortcut: "Ctrl+S",
      icon: "↓",
      available: () => canEdit,
      execute: () => fileActionsRef.current.saveCurrentDrawing?.(),
    },
    {
      id: "files.save-as",
      label: "Save As",
      description: "Save the current drawing to a new file",
      keywords: ["save", "save as", "export file", "file"],
      category: "Files",
      shortcut: "Ctrl+Shift+S",
      icon: "↓",
      available: () => canEdit,
      execute: () => fileActionsRef.current.saveDrawingAs?.(),
    },
    {
      id: "files.open-folder",
      label: "Open Folder",
      description: "Choose a folder for Sketchizi file browsing",
      keywords: ["folder", "directory", "open folder", "files"],
      category: "Files",
      shortcut: "",
      icon: "▰",
      available: () => canEdit,
      execute: () => fileActionsRef.current.openFolderFromDisk?.(),
    },
    {
      id: "files.close-folder",
      label: "Close Folder",
      description: "Close the current Sketchizi folder",
      keywords: ["folder", "directory", "close"],
      category: "Files",
      shortcut: "",
      icon: "▰",
      available: () => canEdit && Boolean(currentFolder),
      execute: () => fileActionsRef.current.closeCurrentFolder?.(),
    },
    {
      id: "export.image",
      label: "Export Image",
      description: "Open Excalidraw's existing image export dialog",
      keywords: ["export", "image", "png", "svg", "jpeg"],
      category: "Export",
      shortcut: "Ctrl+Shift+E",
      icon: "⇩",
      available: () => true,
      execute: () => apiRef.current?.updateScene?.({ appState: { ...apiRef.current.getAppState(), openDialog: { name: "imageExport" } } }),
    },
    {
      id: "application.shortcuts",
      label: "Keyboard Shortcuts",
      description: "Open Sketchizi's keyboard shortcut reference",
      keywords: ["help", "shortcuts", "keyboard", "keys", "reference"],
      category: "Application",
      shortcut: "?",
      icon: "?",
      available: () => true,
      execute: () => openPanel("shortcuts"),
    },
    {
      id: "application.excalidraw-command-palette",
      label: "Open Excalidraw Command Palette",
      description: "Open the command palette built into Excalidraw 0.18",
      keywords: ["excalidraw", "command palette", "native", "commands"],
      category: "Application",
      shortcut: "Ctrl+Shift+P",
      icon: "⚡",
      available: () => true,
      execute: openExcalidrawCommandPalette,
    },
  );

  return commands;
}
