export const categories = [
  "AWS Services",
  "Azure Services",
  "GCP Services",
  "Databases",
  "Networking",
  "Kubernetes",
  "Programming",
  "Architecture",
];

export const icons = [
  { id: "aws", name: "AWS", subtitle: "Amazon Web Services", category: "AWS Services", src: "/icons/aws.svg" },
  { id: "ec2", name: "EC2", subtitle: "Virtual Servers", category: "AWS Services", src: "/icons/aws-ec2.svg" },
  { id: "s3", name: "S3", subtitle: "Object Storage", category: "AWS Services", src: "/icons/aws-s3.svg" },
  { id: "lambda", name: "Lambda", subtitle: "Serverless Compute", category: "AWS Services", src: "/icons/aws-lambda.svg" },
  { id: "rds", name: "RDS", subtitle: "Managed Relational DB", category: "AWS Services", src: "/icons/aws-rds.svg" },
  { id: "dynamodb", name: "DynamoDB", subtitle: "NoSQL Database", category: "AWS Services", src: "/icons/dynamodb.svg" },
  { id: "aurora", name: "Aurora", subtitle: "Cloud Database", category: "AWS Services", src: "/icons/aws-aurora.svg" },
  { id: "elasticache", name: "ElastiCache", subtitle: "In-Memory Cache", category: "AWS Services", src: "/icons/aws-elasticache.svg" },
  { id: "vpc", name: "VPC", subtitle: "Virtual Network", category: "AWS Services", src: "/icons/aws-vpc.svg" },
  { id: "cloudfront", name: "CloudFront", subtitle: "CDN", category: "AWS Services", src: "/icons/aws-cloudfront.svg" },
  { id: "route53", name: "Route 53", subtitle: "DNS Service", category: "AWS Services", src: "/icons/aws-route53.svg" },
  { id: "elb", name: "Elastic Load Balancing", subtitle: "Load Balancer", category: "AWS Services", src: "/icons/aws-elb.svg" },
  { id: "apigateway", name: "API Gateway", subtitle: "API Management", category: "AWS Services", src: "/icons/aws-apigateway.svg" },
  { id: "ecs", name: "ECS", subtitle: "Container Service", category: "AWS Services", src: "/icons/aws-ecs.svg" },
  { id: "eks", name: "EKS", subtitle: "Managed Kubernetes", category: "AWS Services", src: "/icons/aws-eks.svg" },
  { id: "ecr", name: "ECR", subtitle: "Container Registry", category: "AWS Services", src: "/icons/aws-ecr.svg" },
  { id: "fargate", name: "Fargate", subtitle: "Serverless Containers", category: "AWS Services", src: "/icons/aws-fargate.svg" },
  { id: "sns", name: "SNS", subtitle: "Pub/Sub Messaging", category: "AWS Services", src: "/icons/aws-sns.svg" },
  { id: "sqs", name: "SQS", subtitle: "Message Queue", category: "AWS Services", src: "/icons/aws-sqs.svg" },
  { id: "eventbridge", name: "EventBridge", subtitle: "Event Bus", category: "AWS Services", src: "/icons/aws-eventbridge.svg" },
  { id: "cloudwatch", name: "CloudWatch", subtitle: "Monitoring", category: "AWS Services", src: "/icons/aws-cloudwatch.svg" },
  { id: "cloudtrail", name: "CloudTrail", subtitle: "Audit Logs", category: "AWS Services", src: "/icons/aws-cloudtrail.svg" },
  { id: "iam", name: "IAM", subtitle: "Identity & Access", category: "AWS Services", src: "/icons/aws-iam.svg" },
  { id: "cognito", name: "Cognito", subtitle: "User Identity", category: "AWS Services", src: "/icons/aws-cognito.svg" },
  { id: "kms", name: "KMS", subtitle: "Key Management", category: "AWS Services", src: "/icons/aws-kms.svg" },
  { id: "secretsmanager", name: "Secrets Manager", subtitle: "Secrets", category: "AWS Services", src: "/icons/aws-secretsmanager.svg" },
  { id: "efs", name: "EFS", subtitle: "File Storage", category: "AWS Services", src: "/icons/aws-efs.svg" },
  { id: "ebs", name: "EBS", subtitle: "Block Storage", category: "AWS Services", src: "/icons/aws-ebs.svg" },
  { id: "glacier", name: "S3 Glacier", subtitle: "Archive Storage", category: "AWS Services", src: "/icons/aws-glacier.svg" },
  { id: "redshift", name: "Redshift", subtitle: "Data Warehouse", category: "AWS Services", src: "/icons/aws-redshift.svg" },
  { id: "athena", name: "Athena", subtitle: "SQL Analytics", category: "AWS Services", src: "/icons/aws-athena.svg" },
  { id: "kinesis", name: "Kinesis", subtitle: "Streaming Data", category: "AWS Services", src: "/icons/aws-kinesis.svg" },
  { id: "sagemaker", name: "SageMaker", subtitle: "Machine Learning", category: "AWS Services", src: "/icons/aws-sagemaker.svg" },
  { id: "bedrock", name: "Bedrock", subtitle: "Generative AI", category: "AWS Services", src: "/icons/aws-bedrock.svg" },
  { id: "azure", name: "Azure", subtitle: "Microsoft Azure", category: "Azure Services", src: "/icons/azure.svg" },
  { id: "vm", name: "Virtual Machines", subtitle: "Compute", category: "Azure Services", src: "/icons/azure-vm.svg" },
  { id: "blob", name: "Blob Storage", subtitle: "Object Storage", category: "Azure Services", src: "/icons/azure-blob.svg" },
  { id: "functions", name: "Functions", subtitle: "Serverless Compute", category: "Azure Services", src: "/icons/azure-functions.svg" },
  { id: "aks", name: "AKS", subtitle: "Managed Kubernetes", category: "Azure Services", src: "/icons/azure-aks.svg" },
  { id: "acr", name: "Container Registry", subtitle: "Container Registry", category: "Azure Services", src: "/icons/azure-acr.svg" },
  { id: "appservice", name: "App Service", subtitle: "Web Apps", category: "Azure Services", src: "/icons/azure-appservice.svg" },
  { id: "sql", name: "Azure SQL", subtitle: "Relational Database", category: "Azure Services", src: "/icons/azure-sql.svg" },
  { id: "cosmos", name: "Cosmos DB", subtitle: "NoSQL Database", category: "Azure Services", src: "/icons/azure-cosmos.svg" },
  { id: "postgres", name: "Azure Database for PostgreSQL", subtitle: "Managed PostgreSQL", category: "Azure Services", src: "/icons/azure-postgres.svg" },
  { id: "vnet", name: "Virtual Network", subtitle: "Private Networking", category: "Azure Services", src: "/icons/azure-vnet.svg" },
  { id: "frontdoor", name: "Front Door", subtitle: "Global Entry", category: "Azure Services", src: "/icons/azure-frontdoor.svg" },
  { id: "cdn", name: "Azure CDN", subtitle: "Content Delivery", category: "Azure Services", src: "/icons/azure-cdn.svg" },
  { id: "appgateway", name: "Application Gateway", subtitle: "Load Balancer", category: "Azure Services", src: "/icons/azure-appgateway.svg" },
  { id: "loadbalancer", name: "Load Balancer", subtitle: "Traffic Distribution", category: "Azure Services", src: "/icons/azure-loadbalancer.svg" },
  { id: "dns", name: "DNS", subtitle: "DNS Service", category: "Azure Services", src: "/icons/azure-dns.svg" },
  { id: "api", name: "API Management", subtitle: "API Gateway", category: "Azure Services", src: "/icons/azure-api.svg" },
  { id: "eventgrid", name: "Event Grid", subtitle: "Event Routing", category: "Azure Services", src: "/icons/azure-eventgrid.svg" },
  { id: "servicebus", name: "Service Bus", subtitle: "Messaging", category: "Azure Services", src: "/icons/azure-servicebus.svg" },
  { id: "queue", name: "Storage Queues", subtitle: "Message Queue", category: "Azure Services", src: "/icons/azure-queue.svg" },
  { id: "redis", name: "Azure Cache for Redis", subtitle: "In-Memory Cache", category: "Azure Services", src: "/icons/redis.svg" },
  { id: "keyvault", name: "Key Vault", subtitle: "Secrets & Keys", category: "Azure Services", src: "/icons/azure-keyvault.svg" },
  { id: "entra", name: "Microsoft Entra ID", subtitle: "Identity", category: "Azure Services", src: "/icons/azure-entra.svg" },
  { id: "monitor", name: "Azure Monitor", subtitle: "Monitoring", category: "Azure Services", src: "/icons/azure-monitor.svg" },
  { id: "loganalytics", name: "Log Analytics", subtitle: "Observability", category: "Azure Services", src: "/icons/azure-loganalytics.svg" },
  { id: "acr2", name: "Container Apps", subtitle: "Serverless Containers", category: "Azure Services", src: "/icons/azure-acr2.svg" },
  { id: "devops", name: "Azure DevOps", subtitle: "CI/CD", category: "Azure Services", src: "/icons/azure-devops.svg" },
  { id: "synapse", name: "Synapse Analytics", subtitle: "Analytics", category: "Azure Services", src: "/icons/azure-synapse.svg" },
  { id: "datafactory", name: "Data Factory", subtitle: "Data Integration", category: "Azure Services", src: "/icons/azure-datafactory.svg" },
  { id: "ai", name: "Azure AI", subtitle: "AI Services", category: "Azure Services", src: "/icons/azure-ai.svg" },
  { id: "openai", name: "Azure OpenAI", subtitle: "Generative AI", category: "Azure Services", src: "/icons/azure-openai.svg" },
  { id: "eventhubs", name: "Event Hubs", subtitle: "Event Streaming", category: "Azure Services", src: "/icons/azure-eventhubs.svg" },
  { id: "managedgrafana", name: "Managed Grafana", subtitle: "Dashboards", category: "Azure Services", src: "/icons/azure-managedgrafana.svg" },
  { id: "gcp", name: "Google Cloud", subtitle: "Google Cloud Platform", category: "GCP Services", src: "/icons/gcp.svg" },
  { id: "compute", name: "Compute Engine", subtitle: "Virtual Machines", category: "GCP Services", src: "/icons/gcp-compute.svg" },
  { id: "storage", name: "Cloud Storage", subtitle: "Object Storage", category: "GCP Services", src: "/icons/gcp-storage.svg" },
  { id: "functions", name: "Cloud Functions", subtitle: "Serverless Compute", category: "GCP Services", src: "/icons/gcp-functions.svg" },
  { id: "run", name: "Cloud Run", subtitle: "Containers", category: "GCP Services", src: "/icons/gcp-run.svg" },
  { id: "gke", name: "Google Kubernetes Engine", subtitle: "Managed Kubernetes", category: "GCP Services", src: "/icons/gcp-gke.svg" },
  { id: "artifact", name: "Artifact Registry", subtitle: "Container Registry", category: "GCP Services", src: "/icons/gcp-artifact.svg" },
  { id: "sql", name: "Cloud SQL", subtitle: "Relational Database", category: "GCP Services", src: "/icons/gcp-sql.svg" },
  { id: "spanner", name: "Cloud Spanner", subtitle: "Distributed Database", category: "GCP Services", src: "/icons/gcp-spanner.svg" },
  { id: "firestore", name: "Firestore", subtitle: "Document Database", category: "GCP Services", src: "/icons/gcp-firestore.svg" },
  { id: "bigtable", name: "Bigtable", subtitle: "Wide-Column Database", category: "GCP Services", src: "/icons/gcp-bigtable.svg" },
  { id: "memorystore", name: "Memorystore", subtitle: "In-Memory Cache", category: "GCP Services", src: "/icons/gcp-memorystore.svg" },
  { id: "vpc", name: "Virtual Private Cloud", subtitle: "Networking", category: "GCP Services", src: "/icons/gcp-vpc.svg" },
  { id: "lb", name: "Cloud Load Balancing", subtitle: "Load Balancer", category: "GCP Services", src: "/icons/gcp-lb.svg" },
  { id: "cdn", name: "Cloud CDN", subtitle: "Content Delivery", category: "GCP Services", src: "/icons/gcp-cdn.svg" },
  { id: "dns", name: "Cloud DNS", subtitle: "DNS", category: "GCP Services", src: "/icons/gcp-dns.svg" },
  { id: "api", name: "Apigee", subtitle: "API Management", category: "GCP Services", src: "/icons/gcp-api.svg" },
  { id: "pubsub", name: "Pub/Sub", subtitle: "Messaging", category: "GCP Services", src: "/icons/gcp-pubsub.svg" },
  { id: "tasks", name: "Cloud Tasks", subtitle: "Task Queue", category: "GCP Services", src: "/icons/gcp-tasks.svg" },
  { id: "scheduler", name: "Cloud Scheduler", subtitle: "Scheduling", category: "GCP Services", src: "/icons/gcp-scheduler.svg" },
  { id: "monitoring", name: "Cloud Monitoring", subtitle: "Monitoring", category: "GCP Services", src: "/icons/gcp-monitoring.svg" },
  { id: "logging", name: "Cloud Logging", subtitle: "Logs", category: "GCP Services", src: "/icons/gcp-logging.svg" },
  { id: "iam", name: "Cloud IAM", subtitle: "Identity & Access", category: "GCP Services", src: "/icons/gcp-iam.svg" },
  { id: "secret", name: "Secret Manager", subtitle: "Secrets", category: "GCP Services", src: "/icons/gcp-secret.svg" },
  { id: "kms", name: "Cloud KMS", subtitle: "Key Management", category: "GCP Services", src: "/icons/gcp-kms.svg" },
  { id: "bigquery", name: "BigQuery", subtitle: "Data Warehouse", category: "GCP Services", src: "/icons/gcp-bigquery.svg" },
  { id: "dataflow", name: "Dataflow", subtitle: "Data Processing", category: "GCP Services", src: "/icons/gcp-dataflow.svg" },
  { id: "dataproc", name: "Dataproc", subtitle: "Big Data", category: "GCP Services", src: "/icons/gcp-dataproc.svg" },
  { id: "vertex", name: "Vertex AI", subtitle: "Machine Learning", category: "GCP Services", src: "/icons/gcp-vertex.svg" },
  { id: "vision", name: "Vision AI", subtitle: "Computer Vision", category: "GCP Services", src: "/icons/gcp-vision.svg" },
  { id: "cloudarmor", name: "Cloud Armor", subtitle: "Web Security", category: "GCP Services", src: "/icons/gcp-cloudarmor.svg" },
  { id: "postgresql", name: "PostgreSQL", subtitle: "Relational Database", category: "Databases", src: "/icons/postgresql.svg" },
  { id: "mysql", name: "MySQL", subtitle: "Relational Database", category: "Databases", src: "/icons/mysql.svg" },
  { id: "mongodb", name: "MongoDB", subtitle: "Document Database", category: "Databases", src: "/icons/mongodb.svg" },
  { id: "redis", name: "Redis", subtitle: "In-Memory Database", category: "Databases", src: "/icons/redis.svg" },
  { id: "dynamodb", name: "DynamoDB", subtitle: "NoSQL Database", category: "Databases", src: "/icons/dynamodb.svg" },
  { id: "sqlite", name: "SQLite", subtitle: "Embedded Database", category: "Databases", src: "/icons/db-sqlite.svg" },
  { id: "mariadb", name: "MariaDB", subtitle: "Relational Database", category: "Databases", src: "/icons/db-mariadb.svg" },
  { id: "oracle", name: "Oracle", subtitle: "Relational Database", category: "Databases", src: "/icons/db-oracle.svg" },
  { id: "sqlserver", name: "SQL Server", subtitle: "Relational Database", category: "Databases", src: "/icons/db-sqlserver.svg" },
  { id: "cassandra", name: "Cassandra", subtitle: "Wide-Column Database", category: "Databases", src: "/icons/db-cassandra.svg" },
  { id: "neo4j", name: "Neo4j", subtitle: "Graph Database", category: "Databases", src: "/icons/db-neo4j.svg" },
  { id: "elasticsearch", name: "Elasticsearch", subtitle: "Search Database", category: "Databases", src: "/icons/db-elasticsearch.svg" },
  { id: "influxdb", name: "InfluxDB", subtitle: "Time-Series Database", category: "Databases", src: "/icons/db-influxdb.svg" },
  { id: "cockroach", name: "CockroachDB", subtitle: "Distributed SQL", category: "Databases", src: "/icons/db-cockroach.svg" },
  { id: "supabase", name: "Supabase", subtitle: "Postgres Platform", category: "Databases", src: "/icons/db-supabase.svg" },
  { id: "router", name: "Router", subtitle: "Network Routing", category: "Networking", src: "/icons/router.svg" },
  { id: "switch", name: "Switch", subtitle: "LAN Switching", category: "Networking", src: "/icons/switch.svg" },
  { id: "firewall", name: "Firewall", subtitle: "Network Security", category: "Networking", src: "/icons/firewall.svg" },
  { id: "load-balancer", name: "Load Balancer", subtitle: "Traffic Distribution", category: "Networking", src: "/icons/load-balancer.svg" },
  { id: "server", name: "Server", subtitle: "Network Server", category: "Networking", src: "/icons/server.svg" },
  { id: "gateway", name: "Gateway", subtitle: "Network Gateway", category: "Networking", src: "/icons/net-gateway.svg" },
  { id: "vpn", name: "VPN", subtitle: "Secure Tunnel", category: "Networking", src: "/icons/net-vpn.svg" },
  { id: "proxy", name: "Proxy", subtitle: "Traffic Proxy", category: "Networking", src: "/icons/net-proxy.svg" },
  { id: "dns", name: "DNS", subtitle: "Name Resolution", category: "Networking", src: "/icons/net-dns.svg" },
  { id: "cdn", name: "CDN", subtitle: "Content Delivery", category: "Networking", src: "/icons/net-cdn.svg" },
  { id: "internet", name: "Internet", subtitle: "External Network", category: "Networking", src: "/icons/net-internet.svg" },
  { id: "subnet", name: "Subnet", subtitle: "Network Segment", category: "Networking", src: "/icons/net-subnet.svg" },
  { id: "vpc", name: "VPC", subtitle: "Virtual Network", category: "Networking", src: "/icons/net-vpc.svg" },
  { id: "nat", name: "NAT Gateway", subtitle: "Address Translation", category: "Networking", src: "/icons/net-nat.svg" },
  { id: "waf", name: "WAF", subtitle: "Web Application Firewall", category: "Networking", src: "/icons/net-waf.svg" },
  { id: "api-gateway", name: "API Gateway", subtitle: "API Entry Point", category: "Networking", src: "/icons/net-api-gateway.svg" },
  { id: "service-mesh", name: "Service Mesh", subtitle: "Service Networking", category: "Networking", src: "/icons/net-service-mesh.svg" },
  { id: "kubernetes", name: "Kubernetes", subtitle: "Container Orchestration", category: "Kubernetes", src: "/icons/k8s-kubernetes.svg" },
  { id: "pod", name: "Pod", subtitle: "Smallest Workload Unit", category: "Kubernetes", src: "/icons/k8s-pod.svg" },
  { id: "deployment", name: "Deployment", subtitle: "Managed Replica Set", category: "Kubernetes", src: "/icons/k8s-deployment.svg" },
  { id: "service", name: "Service", subtitle: "Stable Network Endpoint", category: "Kubernetes", src: "/icons/k8s-service.svg" },
  { id: "ingress", name: "Ingress", subtitle: "HTTP Routing", category: "Kubernetes", src: "/icons/k8s-ingress.svg" },
  { id: "configmap", name: "ConfigMap", subtitle: "Configuration", category: "Kubernetes", src: "/icons/k8s-configmap.svg" },
  { id: "secret", name: "Secret", subtitle: "Sensitive Configuration", category: "Kubernetes", src: "/icons/k8s-secret.svg" },
  { id: "namespace", name: "Namespace", subtitle: "Cluster Isolation", category: "Kubernetes", src: "/icons/k8s-namespace.svg" },
  { id: "node", name: "Node", subtitle: "Worker Machine", category: "Kubernetes", src: "/icons/k8s-node.svg" },
  { id: "helm", name: "Helm", subtitle: "Package Manager", category: "Kubernetes", src: "/icons/k8s-helm.svg" },
  { id: "etcd", name: "etcd", subtitle: "Cluster State Store", category: "Kubernetes", src: "/icons/k8s-etcd.svg" },
  { id: "operator", name: "Operator", subtitle: "Automation Controller", category: "Kubernetes", src: "/icons/k8s-operator.svg" },
  { id: "statefulset", name: "StatefulSet", subtitle: "Stateful Workloads", category: "Kubernetes", src: "/icons/k8s-statefulset.svg" },
  { id: "daemonset", name: "DaemonSet", subtitle: "Node-Level Workload", category: "Kubernetes", src: "/icons/k8s-daemonset.svg" },
  { id: "job", name: "Job", subtitle: "Batch Workload", category: "Kubernetes", src: "/icons/k8s-job.svg" },
  { id: "javascript", name: "JavaScript", subtitle: "Programming Language", category: "Programming", src: "/icons/prog-javascript.svg" },
  { id: "typescript", name: "TypeScript", subtitle: "Programming Language", category: "Programming", src: "/icons/prog-typescript.svg" },
  { id: "python", name: "Python", subtitle: "Programming Language", category: "Programming", src: "/icons/prog-python.svg" },
  { id: "java", name: "Java", subtitle: "Programming Language", category: "Programming", src: "/icons/prog-java.svg" },
  { id: "csharp", name: "C#", subtitle: "Programming Language", category: "Programming", src: "/icons/prog-csharp.svg" },
  { id: "cpp", name: "C++", subtitle: "Programming Language", category: "Programming", src: "/icons/prog-cpp.svg" },
  { id: "c", name: "C", subtitle: "Programming Language", category: "Programming", src: "/icons/prog-c.svg" },
  { id: "go", name: "Go", subtitle: "Programming Language", category: "Programming", src: "/icons/prog-go.svg" },
  { id: "rust", name: "Rust", subtitle: "Programming Language", category: "Programming", src: "/icons/prog-rust.svg" },
  { id: "php", name: "PHP", subtitle: "Programming Language", category: "Programming", src: "/icons/prog-php.svg" },
  { id: "ruby", name: "Ruby", subtitle: "Programming Language", category: "Programming", src: "/icons/prog-ruby.svg" },
  { id: "kotlin", name: "Kotlin", subtitle: "Programming Language", category: "Programming", src: "/icons/prog-kotlin.svg" },
  { id: "swift", name: "Swift", subtitle: "Programming Language", category: "Programming", src: "/icons/prog-swift.svg" },
  { id: "react", name: "React", subtitle: "UI Library", category: "Programming", src: "/icons/prog-react.svg" },
  { id: "node", name: "Node.js", subtitle: "JavaScript Runtime", category: "Programming", src: "/icons/prog-node.svg" },
  { id: "dotnet", name: ".NET", subtitle: "Application Platform", category: "Programming", src: "/icons/prog-dotnet.svg" },
  { id: "spring", name: "Spring", subtitle: "Java Framework", category: "Programming", src: "/icons/prog-spring.svg" },
  { id: "git", name: "Git", subtitle: "Version Control", category: "Programming", src: "/icons/prog-git.svg" },
  { id: "docker", name: "Docker", subtitle: "Container Platform", category: "Programming", src: "/icons/prog-docker.svg" },
  { id: "client", name: "Client", subtitle: "User Device", category: "Architecture", src: "/icons/arch-client.svg" },
  { id: "browser", name: "Web Browser", subtitle: "Application Client", category: "Architecture", src: "/icons/arch-browser.svg" },
  { id: "web-server", name: "Web Server", subtitle: "HTTP Server", category: "Architecture", src: "/icons/arch-web-server.svg" },
  { id: "app-server", name: "Application Server", subtitle: "Application Runtime", category: "Architecture", src: "/icons/arch-app-server.svg" },
  { id: "database", name: "Database", subtitle: "Data Store", category: "Architecture", src: "/icons/arch-database.svg" },
  { id: "cache", name: "Cache", subtitle: "Fast Data Layer", category: "Architecture", src: "/icons/arch-cache.svg" },
  { id: "queue", name: "Message Queue", subtitle: "Async Messaging", category: "Architecture", src: "/icons/arch-queue.svg" },
  { id: "microservices", name: "Microservices", subtitle: "Service Architecture", category: "Architecture", src: "/icons/arch-microservices.svg" },
  { id: "monolith", name: "Monolith", subtitle: "Single Application", category: "Architecture", src: "/icons/arch-monolith.svg" },
  { id: "api", name: "API", subtitle: "Application Interface", category: "Architecture", src: "/icons/arch-api.svg" },
  { id: "load-balancer", name: "Load Balancer", subtitle: "Traffic Distribution", category: "Architecture", src: "/icons/load-balancer.svg" },
  { id: "cdn", name: "CDN", subtitle: "Edge Delivery", category: "Architecture", src: "/icons/arch-cdn.svg" },
  { id: "object-storage", name: "Object Storage", subtitle: "File & Object Data", category: "Architecture", src: "/icons/arch-object-storage.svg" },
  { id: "container", name: "Container", subtitle: "Isolated Application", category: "Architecture", src: "/icons/arch-container.svg" },
  { id: "cluster", name: "Cluster", subtitle: "Compute Group", category: "Architecture", src: "/icons/arch-cluster.svg" },
  { id: "user", name: "User", subtitle: "System Actor", category: "Architecture", src: "/icons/arch-user.svg" },
  { id: "internet", name: "Internet", subtitle: "External Network", category: "Architecture", src: "/icons/arch-internet.svg" },
  { id: "cloud", name: "Cloud", subtitle: "Cloud Environment", category: "Architecture", src: "/icons/arch-cloud.svg" },
  { id: "region", name: "Region", subtitle: "Deployment Region", category: "Architecture", src: "/icons/arch-region.svg" },
  { id: "availability-zone", name: "Availability Zone", subtitle: "Fault Domain", category: "Architecture", src: "/icons/arch-availability-zone.svg" },
];
